/**
 * Codemod: react-native-svg icon components → DOM `<svg>` components.
 *
 * Sources (read-only):
 *   E:\GitHub\fx\libs\component-library\src\lib\icons\icons.tsx   (63 `Fx*Icon`s)
 *   E:\GitHub\fx\apps\box\src\components\Icons.tsx                (Logo, BloxIcon, …, DynamicIcon)
 * Output: src/icons/generated/<Name>.tsx (one component per file) + src/icons/generated/index.ts
 *
 * Transform: `<Path` → `<path`, `<Circle` → `<circle`; the root `fill="none"` is dropped so icons
 * default to `currentColor` (FxSvg sets `fill` on the <svg>; paths inherit it). Only these two
 * element types and the attributes width/height/viewBox/fill/fillRule/clipRule/d/cx/cy/r appear in
 * the sources — the script refuses to run if it meets anything else.
 *
 * Run: `npm run icons:generate -w packages/fx-ui` (Node ≥ 22.6 type-stripping; no deps).
 * Override sources with FX_ICONS_LIB / FX_ICONS_BOX env vars.
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(here, '../src/icons/generated');

const SOURCES: { path: string; label: string }[] = [
  {
    path: process.env.FX_ICONS_LIB ?? 'E:/GitHub/fx/libs/component-library/src/lib/icons/icons.tsx',
    label: 'libs/component-library/src/lib/icons/icons.tsx',
  },
  {
    path: process.env.FX_ICONS_BOX ?? 'E:/GitHub/fx/apps/box/src/components/Icons.tsx',
    label: 'apps/box/src/components/Icons.tsx',
  },
];

const ALLOWED_ELEMENTS = new Set(['FxSvg', 'Path', 'Circle']);
const ALLOWED_ATTRS = new Set([
  'width',
  'height',
  'viewBox',
  'fill',
  'fillRule',
  'clipRule',
  'd',
  'cx',
  'cy',
  'r',
]);

interface IconBlock {
  name: string;
  params: string;
  body: string;
  source: string;
}

function extractBlocks(src: string, label: string): IconBlock[] {
  const re = /^export const (\w+) = \(([^)]*)\) => \(\n([\s\S]*?)^\);/gm;
  const blocks: IconBlock[] = [];
  for (const m of src.matchAll(re)) {
    const [, name, params, body] = m;
    if (!name || params === undefined || body === undefined) continue;
    blocks.push({ name, params: params.trim(), body, source: label });
  }
  return blocks;
}

function validate(block: IconBlock): void {
  for (const m of block.body.matchAll(/<\/?([A-Za-z][\w.]*)/g)) {
    const el = m[1];
    if (el && !ALLOWED_ELEMENTS.has(el)) {
      throw new Error(`${block.name}: unsupported element <${el}> — extend the codemod`);
    }
  }
  for (const m of block.body.matchAll(/\s([A-Za-z][\w-]*)=/g)) {
    const attr = m[1];
    if (attr && !ALLOWED_ATTRS.has(attr)) {
      throw new Error(`${block.name}: unsupported attribute "${attr}" — extend the codemod`);
    }
  }
}

function transformBody(body: string): string {
  return (
    body
      .replace(/<Path\b/g, '<path')
      .replace(/<Circle\b/g, '<circle')
      // root fill="none" → inherit currentColor (FxSvg default). Keep fills on child paths.
      .replace(/(<FxSvg\b[^>]*?)\sfill="none"/g, '$1')
  );
}

function transformParams(params: string): string {
  // `props: FxSvgProps` and `{ iconPath, ...props }: FxSvgProps & { iconPath: string }` both pass through.
  return params;
}

function render(block: IconBlock): string {
  const body = transformBody(block.body);
  return [
    `// AUTO-GENERATED by scripts/convert-rn-icons.ts from ${block.source} - do not edit.`,
    `import { FxSvg, type FxSvgProps } from '../FxSvg.js';`,
    ``,
    `export const ${block.name} = (${transformParams(block.params)}) => (`,
    body.trimEnd(),
    `);`,
    ``,
  ].join('\n');
}

function main(): void {
  const blocks: IconBlock[] = [];
  for (const s of SOURCES) {
    const src = readFileSync(s.path, 'utf8');
    const found = extractBlocks(src, s.label);
    if (found.length === 0) throw new Error(`no icon components found in ${s.path}`);
    blocks.push(...found);
  }
  const names = new Set<string>();
  for (const b of blocks) {
    if (names.has(b.name)) throw new Error(`duplicate icon name ${b.name}`);
    names.add(b.name);
    validate(b);
  }

  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });
  for (const b of blocks) {
    writeFileSync(join(OUT_DIR, `${b.name}.tsx`), render(b), 'utf8');
  }
  const index = [
    `// AUTO-GENERATED by scripts/convert-rn-icons.ts - do not edit.`,
    ...blocks.map((b) => `export * from './${b.name}.js';`),
    ``,
  ].join('\n');
  writeFileSync(join(OUT_DIR, 'index.ts'), index, 'utf8');

  const written = readdirSync(OUT_DIR).filter((f) => f.endsWith('.tsx')).length;
  console.log(`icons: wrote ${written} components to ${OUT_DIR}`);
  for (const s of SOURCES) {
    console.log(`  ${blocks.filter((b) => b.source === s.label).length} from ${s.label}`);
  }
}

main();
